### ISSUE TITLE
Add SSL and VHost to php -S

### ISSUE THREAD

**Issue by maliksvd** [wordplate/wordplate#208] opened 2018-07-31 10:53 UTC
Hello,

I just started using Wordplate.
However when using an internal php server I find myself blocked.
I would like to create a Vhost with an https / ssl.
I already added my vhost in the files hosts etc.

I would like what was the procedure to follow for this, I have already searched in the existing issues as well as on the documentation, without success.

Or if there is an alerniatve to the use of an internal php server.

Waiting for an answer.

**Comment by vinkla** [comment] 2018-07-31 11:07
If you're running macOS I would suggest you take a look at [Laravel Valet](https://laravel.com/docs/5.6/valet) which has support for SSL certificates built-in. If I remember correctly there should be alternatives for Windows.

**Comment by maliksvd** [comment] 2018-07-31 16:42
Ok, thanks.

When my Valet is configured must I still `php -S locahost:8000 -t public` ? 

Because i have a blank page when Valet running in "public" folder.

**Comment by maliksvd** [comment] 2018-07-31 16:51
Update : When I go to my Valet I get this. 

![
](http://i.prntscr.com/S_ktWTPeQa2FrxvoK1FDwg.png)

**Comment by vinkla** [comment] 2018-07-31 19:51
Try using the local driver for WordPlate. Currently writing this on a mobile. You’ll find it in the documentation. If you change the WordPress path you might need to update the driver.

**Comment by maliksvd** [comment] 2018-07-31 20:10
Ok, so now i have a "ERR_TOO_MANY_REDIRECTS" error.

I don't if this error provide to Valet or Wordplate.

**Comment by maliksvd** [comment] 2018-07-31 20:40
I have already add the file into the project folder 

https://github.com/wordplate/valet but nothin happend

**Comment by maliksvd** [comment] 2018-07-31 23:28
I also add LocalValetDriver to /Valet/Drivers folder and i have always error.

ERR_TOO_MANY_REDIRECTS

**Comment by vinkla** [comment] 2018-08-01 07:31
> When my Valet is configured must I still `php -S locahost:8000 -t public`?

No, this is no longer necessary if you use Valet.


> I also add LocalValetDriver to /Valet/Drivers folder and i have always error.

Did you update the WordPress path within the Valet driver?

https://github.com/wordplate/valet/blob/e11b426ddebc8ee96d1826217704deb3b66532f6/LocalValetDriver.php#L69

**Comment by maliksvd** [comment] 2018-08-01 08:00
I don't understand what is the the $uri,` '/wordpress/')

If on my mac my project is in /Users/Me/Project/WordplateFolder/

I must type this path ?

**Comment by maliksvd** [comment] 2018-08-01 08:27
Now this the default path.
![
](https://i.imgur.com/n85YRmN.png)

But with the default uri doesn't work.
I have always the error.

**Comment by vinkla** [comment] 2018-08-01 08:37
In your [previous screenshot](https://camo.githubusercontent.com/142f467a146e49b98b5ce64418d820e722cb656a/687474703a2f2f692e70726e747363722e636f6d2f70675a614f49557453494f76693639304452784961412e706e67) the WordPress directory seems to be called `wp`. You'll need to visit `/wordpress/wp-admin/install.php` in order to install WordPress with WordPlate.

**Comment by maliksvd** [comment] 2018-08-01 08:47
Work with /wordpress in chrome but I want the wordpress address to point in / and not in the subfolder address

**Comment by vinkla** [comment] 2018-08-01 08:53
> Work with /wordpress in chrome... 

Great! I'll go ahead and close this issue.

> ...but I want the wordpress address to point in / and not in the subfolder address

This is the expected behaviour with WordPlate. It isn't really an issue since this will only affect the administrators of your website. The users will still visit the page on the root domain.

**Closed by vinkla** 2018-08-01 08:53 UTC
Labels: question

**Comment by maliksvd** [comment] 2018-08-02 08:46
Hi, after a reboot when i access to my domain chrome return ERR_CONNECTION_TIMED_OUT
